language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer # Updates JDK 8 to the latest available.

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  - ./gradlew test run ktlintCheck checkstyle
